version: '3.9'

services:
  django:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./:/api-server
    working_dir: /api-server
    tty: true
    env_file: .env
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
